import type { User } from '@/types/userTypes';

// This is the original mock data, now used for seeding the database.
export const mockUsers: Omit<User, 'id' | 'password'>[] = [
  {
    username: 'alex',
    fullName: 'alex',
    email: 'alex@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/1/200/200',
    bio: 'CS student passionate about open source and building cool things. I can help with backend development and love learning about new design trends.',
    skillsOffered: ['Python', 'Algorithms', 'Node.js', 'SQL'],
    skillsWanted: ['UI/UX Design', 'Figma', 'React'],
    learningStyle: ['Hands-on', 'Fast-paced'],
    availability: 'Weekends, and weekday evenings after 6 PM PT.',
  },
  {
    username: 'brian',
    fullName: 'brian',
    email: 'brian@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/2/200/200',
    bio: 'Design student with a knack for creating intuitive and beautiful user interfaces. Looking to get my hands dirty with some real code.',
    skillsOffered: ['UI/UX Design', 'Figma', 'Branding', 'User Research'],
    skillsWanted: ['Programming', 'Python', 'Web Development'],
    learningStyle: ['Visual', 'Discussion-based'],
    availability: 'Most afternoons.',
  },
  {
    username: 'casey',
    fullName: 'casey',
    email: 'casey@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/3/200/200',
    bio: 'Frontend developer who loves React. I want to expand my skills into mobile development.',
    skillsOffered: ['React', 'JavaScript', 'HTML/CSS', 'Frontend Development'],
    skillsWanted: ['Swift', 'iOS Development', 'Kotlin'],
    learningStyle: ['Step-by-step', 'Hands-on'],
    availability: 'Tuesdays and Thursdays.',
  },
  {
    username: 'drew',
    fullName: 'drew',
    email: 'drew@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/4/200/200',
    bio: 'Mobile dev learning my way around Android. I can help with Java and Kotlin, but need help with server-side logic.',
    skillsOffered: ['Kotlin', 'Android Development', 'Java'],
    skillsWanted: ['Node.js', 'APIs', 'SQL'],
    learningStyle: ['Concept-first'],
    availability: 'Flexible.',
  },
  {
    username: 'emily',
    fullName: 'emily',
    email: 'emily@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/5/200/200',
    bio: 'Data scientist in training. I can teach you all about pandas and scikit-learn. I need to get better at visualizing my data.',
    skillsOffered: ['Python', 'Data Analysis', 'Machine Learning'],
    skillsWanted: ['D3.js', 'Data Visualization', 'Frontend Development'],
    learningStyle: ['Visual', 'Hands-on'],
    availability: 'Weekends only.',
  },
  {
    username: 'frank',
    fullName: 'frank',
    email: 'frank@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/6/200/200',
    bio: 'Product manager trying to understand the technical side better. I can offer insights into product strategy and user feedback analysis.',
    skillsOffered: ['Product Management', 'Agile', 'User Feedback'],
    skillsWanted: ['JavaScript', 'APIs', 'Database basics'],
    learningStyle: ['Concept-first', 'Discussion-based'],
    availability: 'Monday evenings',
  },
  {
    username: 'grace',
    fullName: 'grace',
    email: 'grace@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/7/200/200',
    bio: 'I am a data analyst who is good with SQL and Tableau. I would like to learn python for data science.',
    skillsOffered: ['SQL', 'Tableau', 'Data Analysis'],
    skillsWanted: ['Python', 'Pandas', 'Machine Learning'],
    learningStyle: ['Step-by-step', 'Hands-on'],
    availability: 'Wednesday and Friday mornings',
  },
  {
    username: 'heidi',
    fullName: 'heidi',
    email: 'heidi@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/8/200/200',
    bio: 'DevOps engineer with experience in AWS and Docker. I want to learn more about front-end frameworks.',
    skillsOffered: ['AWS', 'Docker', 'CI/CD', 'Terraform'],
    skillsWanted: ['React', 'Vue.js', 'Next.js'],
    learningStyle: ['Hands-on', 'Fast-paced'],
    availability: 'Flexible on weekends',
  },
  {
    username: 'ivan',
    fullName: 'ivan',
    email: 'ivan@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/9/200/200',
    bio: 'I am a writer and can help with copywriting and content strategy. I want to build my own blog from scratch.',
    skillsOffered: ['Copywriting', 'Content Strategy', 'SEO basics'],
    skillsWanted: ['HTML/CSS', 'JavaScript', 'WordPress'],
    learningStyle: ['Visual', 'Step-by-step'],
    availability: 'Weekdays after 7 PM ET.',
  },
  {
    username: 'judy',
    fullName: 'judy',
    email: 'judy@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/10/200/200',
    bio: 'Cybersecurity analyst. I can teach about network security and ethical hacking. I want to learn about mobile app security.',
    skillsOffered: ['Network Security', 'Ethical Hacking', 'Penetration Testing'],
    skillsWanted: ['iOS Security', 'Android Security', 'Reverse Engineering'],
    learningStyle: ['Concept-first', 'Hands-on'],
    availability: 'Saturdays',
  },
  {
    username: 'karl',
    fullName: 'karl',
    email: 'karl@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/11/200/200',
    bio: 'UX researcher. I can guide you through user interviews and usability testing. I am interested in learning data visualization.',
    skillsOffered: ['UX Research', 'Usability Testing', 'User Personas'],
    skillsWanted: ['D3.js', 'Tableau', 'Data Storytelling'],
    learningStyle: ['Discussion-based', 'Visual'],
    availability: 'Flexible',
  },
  {
    username: 'linda',
    fullName: 'linda',
    email: 'linda@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/12/200/200',
    bio: 'I am a game developer using Unity and C#. I want to learn about game design principles.',
    skillsOffered: ['Unity', 'C#', '3D Modeling'],
    skillsWanted: ['Game Design', 'Level Design', 'Narrative Design'],
    learningStyle: ['Hands-on'],
    availability: 'Weekends',
  },
  {
    username: 'mike',
    fullName: 'mike',
    email: 'mike@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/13/200/200',
    bio: 'Cloud architect with experience in Google Cloud Platform. Looking to learn more about container orchestration.',
    skillsOffered: ['GCP', 'Cloud Architecture', 'BigQuery'],
    skillsWanted: ['Kubernetes', 'Docker Swarm', 'Service Mesh'],
    learningStyle: ['Concept-first', 'Fast-paced'],
    availability: 'Monday, Wednesday, Friday evenings',
  },
  {
    username: 'nancy',
    fullName: 'nancy',
    email: 'nancy@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/14/200/200',
    bio: 'I am a tester and I am good at automation with Selenium. I want to learn performance testing.',
    skillsOffered: ['QA', 'Selenium', 'Test Automation'],
    skillsWanted: ['JMeter', 'LoadRunner', 'Performance Testing'],
    learningStyle: ['Step-by-step', 'Hands-on'],
    availability: 'Tuesdays and Thursdays',
  },
  {
    username: 'oscar',
    fullName: 'oscar',
    email: 'oscar@skillissue.com',
    avatarUrl: 'https://picsum.photos/seed/15/200/200',
    bio: 'I am a photographer and I can teach you how to use a camera and edit photos. I want to create my own portfolio website.',
    skillsOffered: ['Photography', 'Lightroom', 'Photoshop'],
    skillsWanted: ['HTML/CSS', 'Web Design', 'JavaScript'],
    learningStyle: ['Visual', 'Hands-on'],
    availability: 'Flexible on weekends',
  },
];
